services:
  go-app:
    container_name: go-app
    image: go-api-tutorial
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - go_db
    environment:
      DB_HOST: go_db
      DB_PORT: "5432"
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: postgres
    restart: unless-stopped

  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: boni.leonardor@outlook.com
      PGADMIN_DEFAULT_PASSWORD: 123@mudar
    ports:
      - "5050:80"
    depends_on:
      - go_db

volumes:
  pgdata: